{% set name = "qwt" %}
{% set version = "6.1.3" %}
{% set md5 = '19d1f5fa5e22054d22ee3accc37c54ba' %}

package:
  name: qwt
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://sourceforge.net/projects/qwt/files/qwt/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  md5: {{ md5 }}
  patches:
    # Can't seem to avoid /usr/local/ install without patch
    - qwtconfig.pri.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - qt 4.8.*
  run:
    - qt 4.8.*

test:
  commands:
    - test -f ${PREFIX}/lib/libqwt.so  # [linux]
    - test -f ${PREFIX}/lib/libqwt.dylib  # [osx]

about:
  home: http://qwt.sourceforge.net/ 
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Qt widgets for technical applications. 
  doc_url: http://qwt.sourceforge.net/
  dev_url: https://sourceforge.net/projects/qwt/

extra:
  recipe-maintainers:
    - ceholden
