{% set name = "qwt" %}
{% set version = "6.1.3" %}
{% set md5 = '19d1f5fa5e22054d22ee3accc37c54ba' %}

package:
  name: qwt
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://sourceforge.net/projects/qwt/files/qwt/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  md5: {{ md5 }}
  patches:
    # Can't seem to avoid /usr/local/ install without patch
    - qwtconfig.pri.patch
    # build in release mode
    - windows.patch

build:
  number: 3
  skip: true  # [win and py36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - qt 5.9.*
  host:
    - python  # [win]
  run:
    - qt 5.9.*

test:
  requires:
    - python {{ os.environ.get('PY_VER', '') + '*' }}  # [win]
  commands:
    - test -f ${PREFIX}/lib/libqwt.so  # [linux]
    - test -f ${PREFIX}/lib/libqwt.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\include\\qwt.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\qwt.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\qwt.lib exit 1  # [win]

about:
  home: http://qwt.sourceforge.net/
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Qt widgets for technical applications.
  doc_url: http://qwt.sourceforge.net/
  dev_url: https://sourceforge.net/projects/qwt/

extra:
  recipe-maintainers:
    - ceholden
    - jschueller
    - marcelotrevisani
    - dakcarto
