travis:
  secure:
    BINSTAR_TOKEN: aJNGBZasn26tIdHyZlq+Kl+PLeqkcyf66M/Gn3XixTpVNZpHX2Un/1lH7L+XR4LaePA0OJsM04C29F7n85FRsfqmry1Qaz+KOlIA39aZbasAtpjgN37JcYkRHUESNXMI/Kgu1Nce2uU2vlRJU9szIZhRrbXi2tboSFEVVYMGz9+C7MnHHDFlRgJpE2dQon03LKIjRJrUQ5K1ek2oNGxPjOxYGvXGn6OYBkV1V9ZedWiXVN6oY3dbXYP3Iw9+b1pAO1DK3wwklhsoY7al4LKfTwbwHSLf0rzLgLKU4yLOfQcSe/q/NepZh29Ngaf7W18CMln4cPnxaaLFV4TVBEvDKv0Y+tMbgh793EJeXWv3ZTok1aRzeYtFYBwZkSV1lrNpV1FWrXzCrxchBc0grJ+Sg+oawXCkPKv/nk+H4ix3IAlFfXMHPfSeihkuBTQYvToQn5ASZ3Iep4n0TsAy1aidOiH1byTO4p6AYbTRNRlul/YSh0AB/6vb+5PG+8k8bWt5s6O1Abwj3lZVwu7LlqZHx2mDeOm+iLazj4taGIrqLeEUT+RZe2di+BY8yrsy16iadRLVLVSqMUjn8GpfUq5cTPMmBYjumtVKrWQ0QvH5IOf01xstkXIMCvIPvANGkLRESAsEV4g8WKwPpJCHylDW2gAtzPLcU1MF4dYWuxXarn4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
